### ISSUE TITLE
new champion masteries endpoint

### ISSUE THREAD

**Issue by yawhide** [atuleu/go-lol#2]
Hello,

Would it be possible for you to add the new champion masteries endpoint?

https://developer.riotgames.com/api/methods#!/1071

thanks!

**Comment by atuleu** [comment]
Hi,

Unfortunately this project is not in my top priority list ( I am finalizing my PhD thesis over the next months).

However it would not be difficult to add some structures  that would represent this API. You should only need to add a structure that will Unmarshall the json you would get from the Riot API, and add a few func to APIEndpoint to get those structure. Its pretty straight forward and there is no magic. 

Actually it would not have even be useful to make a go specific package for the riot API, as getting RESTfull data is easy and json is standard in golang. The only reason of that library is that the APIEndpoint limits the number of request you make to meet riot requirement, letting you forget abouth those 419 errors.

**Comment by yawhide** [comment]
Thanks for responding. 
Yeah, only reason why I ask was so I didn't have to re-implement the rate limiter. 
I'll take your advice ad extend your lib.

**Comment by atuleu** [comment]
Hi,

So Finally I wanted to play a bit with it,

please check branch dev-#2 it should have what you are looking for

**Comment by atuleu** [comment]
Hi,

So I had a bit of time and will to implement it. result is in the branch master ( a574d32c66420b8bb9299f235e922598626561ef )

You will also found two new example to test the Champion Mastery API and one to store locally an API Key

bests,

**Comment by yawhide** [comment]
thank you very much!

**Comment by yawhide** [comment]
i am having trouble setting up this xdg thing. I dont know what to put where...
